blank_issues_enabled: false
contact_links:
  - name: ü§ñ –ü–æ–º–æ—â—å –ø–æ –∫–ª–∞—Å—Å–∏—Ñ–∏–∫–∞—Ü–∏–∏ issue
    url: https://github.com/Sonya108/supreme-funicular/wiki/Issue-Guide
    about: –£–∑–Ω–∞–π—Ç–µ, –∫–∞–∫ –ø—Ä–∞–≤–∏–ª—å–Ω–æ –æ—Ñ–æ—Ä–º–ª—è—Ç—å issues
  - name: ‚ùì –í–æ–ø—Ä–æ—Å—ã –∏ –æ–±—Å—É–∂–¥–µ–Ω–∏—è
    url: https://github.com/Sonya108/supreme-funicular/discussions
    about: –î–ª—è –≤–æ–ø—Ä–æ—Å–æ–≤ –∏—Å–ø–æ–ª—å–∑—É–π—Ç–µ Discussions –≤–º–µ—Å—Ç–æ Issues
